##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://kak0490.github.io
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /panama_railroad
# location of code, the full url to your github repository
source-code: https://github.com/kak0490/panama_railroad

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Panama Railroad
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: 
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: Take a journey through the history of the Panama Railroad, the first transcontinental railroad, with this digital collection of photographs, maps, and documents.
keywords: panama railroad, panama canal, railroad construction, 19th century, photography, maps, documents, colon 
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: kak0490

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: Panama_Railroad
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
# page_gen:
#   - data: 'demo-metadata'
#     template: 'item'
#     name: 'objectid'
#     dir: 'items'
#     extension: 'html' 
#     filter: 'objectid'  

##########
# ORGANIZATION SETTINGS
#
# Enter name and link for your organization (replacing the name and links below)
# These values will be used in attribution and data 
organization-name: 
organization-link: 
# Add logo image links if you would like them to appear in banner and footer. Delete or leave blank to remove logos.
organization-logo-banner: https://www.panamarailroad.org/misc/prr-logo.jpg
organization-logo-nav: https://kak0490.github.io/panama_railroad/

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# Library directory location. This allows you to customize where the standard assets are found.
# provide a relative path in this repository or full url 
lib-assets: /assets/lib
# ignore stuff
exclude: [docs/, Rakefile, rakelib/, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md]
# compress CSS output
sass:
  style: compressed
